//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentMonitoringSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassAndSectionDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClassAndSectionDetail()
        {
            this.Students = new HashSet<Student>();
            this.Studentsses = new HashSet<Studentss>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public string CampusID { get; set; }
        public Nullable<int> ClassID { get; set; }
    
        public virtual Campu Campu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
        public virtual Section Section { get; set; }
        public virtual Teacher Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Studentss> Studentsses { get; set; }
        public virtual Class Class { get; set; }
        public virtual AddClass AddClass { get; set; }
    }
}
