//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentMonitoringSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverVehicle
    {
        public string VechicleID { get; set; }
        public Nullable<int> DriverID { get; set; }
        public string Model { get; set; }
        public string NoOfSeats { get; set; }
        public string VehicleCompany { get; set; }
        public string VehicleName { get; set; }
    
        public virtual Driver Driver { get; set; }
    }
}
