//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentMonitoringSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamsTimeTable
    {
        public int ID { get; set; }
        public Nullable<int> ExamsTypeID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> StartTimeHour { get; set; }
        public Nullable<int> StratTimeMinute { get; set; }
        public Nullable<int> EndTimeHour { get; set; }
        public Nullable<int> EndTimeMinuts { get; set; }
        public string Date { get; set; }
        public string CampusID { get; set; }
    
        public virtual Campu Campu { get; set; }
        public virtual Class Class { get; set; }
        public virtual Hour Hour { get; set; }
        public virtual Hour Hour1 { get; set; }
        public virtual Minute Minute { get; set; }
        public virtual Minute Minute1 { get; set; }
        public virtual ExamsType ExamsType { get; set; }
        public virtual subject subject { get; set; }
    }
}
