//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentMonitoringSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoticsBoard
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public string Date { get; set; }
        public string CampusID { get; set; }
        public Nullable<int> UserType { get; set; }
    
        public virtual Campu Campu { get; set; }
        public virtual NoticeBoardUserType NoticeBoardUserType { get; set; }
    }
}
