//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentMonitoringSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentsMonitringSystemEntities : DbContext
    {
        public StudentsMonitringSystemEntities()
            : base("name=StudentsMonitringSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Campu> Campus { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Principle> Principles { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Parent> Parents { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<ClassAndSectionDetail> ClassAndSectionDetails { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<NoticsBoard> NoticsBoards { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<DriverVehicle> DriverVehicles { get; set; }
        public virtual DbSet<Parentss> Parentsses { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Studentss> Studentsses { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<AddClass> AddClasses { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<SubjectTimeTable> SubjectTimeTables { get; set; }
        public virtual DbSet<AmAndPm> AmAndPms { get; set; }
        public virtual DbSet<Day> Days { get; set; }
        public virtual DbSet<Hour> Hours { get; set; }
        public virtual DbSet<Minute> Minutes { get; set; }
        public virtual DbSet<ExamsTimeTable> ExamsTimeTables { get; set; }
        public virtual DbSet<ExamsType> ExamsTypes { get; set; }
        public virtual DbSet<InvoiceInformation> InvoiceInformations { get; set; }
        public virtual DbSet<PaymentInformation> PaymentInformations { get; set; }
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<SubjectTeacher> SubjectTeachers { get; set; }
        public virtual DbSet<NoticeBoardUserType> NoticeBoardUserTypes { get; set; }
        public virtual DbSet<Assignment> Assignments { get; set; }
        public virtual DbSet<subject> subjects { get; set; }
        public virtual DbSet<StudentAttendance> StudentAttendances { get; set; }
        public virtual DbSet<SubjectTimeTable1> SubjectTimeTable1 { get; set; }
    }
}
