//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentMonitoringSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Studentss
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> ClassSectionID { get; set; }
        public string IsApproved { get; set; }
        public Nullable<int> ParentsID { get; set; }
    
        public virtual ClassAndSectionDetail ClassAndSectionDetail { get; set; }
        public virtual Parentss Parentss { get; set; }
        public virtual User User { get; set; }
        public virtual Class Class { get; set; }
    }
}
