//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentMonitoringSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectTimeTable
    {
        public int ID { get; set; }
        public string CampusID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> DayID { get; set; }
        public Nullable<int> StartHourID { get; set; }
        public Nullable<int> StartMintID { get; set; }
        public Nullable<int> EndHourID { get; set; }
        public Nullable<int> EndMintID { get; set; }
        public Nullable<int> StartOClockID { get; set; }
        public Nullable<int> EmdOClockID { get; set; }
        public Nullable<int> ClassID { get; set; }
    
        public virtual Campu Campu { get; set; }
        public virtual Section Section { get; set; }
        public virtual AmAndPm AmAndPm { get; set; }
        public virtual AmAndPm AmAndPm1 { get; set; }
        public virtual Day Day { get; set; }
        public virtual Hour Hour { get; set; }
        public virtual Hour Hour1 { get; set; }
        public virtual Minute Minute { get; set; }
        public virtual Minute Minute1 { get; set; }
        public virtual Class Class { get; set; }
        public virtual subject subject { get; set; }
    }
}
