//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentMonitoringSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectTimeTable1
    {
        public int ID { get; set; }
        public string CampusID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public string Days { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public Nullable<int> ClassID { get; set; }
    
        public virtual Campu Campu { get; set; }
        public virtual Class Class { get; set; }
        public virtual Section Section { get; set; }
        public virtual subject subject { get; set; }
    }
}
